### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [poolqf/FillableLoaders#11]
`CocoaPods` and `Carthage` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by polqf** [comment]
Yeah, of course not everybody is Cocoapods/Carthage user, but as there is a `Source` folder in the repo, so I thought that would be enough.

Anyway, I like the idea of having a Manual installation section. I'm gonna do it now

**Comment by lfarah** [comment]
@poolqf I'm glad you changed your idea. I remember when I was new into iOS programming and those readmes without a Manual Installation always got me lost.
I still see nowadays many libs with people opening issues saying that they don't know how to use CocoaPods or Carthage and they needed help to install it

Thanks! 😄
