### ISSUE TITLE
Swift 3 soon?

### ISSUE THREAD

**Issue by aricarmo** [poolqf/FillableLoaders#14]

**Comment by polqf** [comment]
I'll create a branch ASAP

**Comment by lfarah** [comment]
Thank you @poolqf 🎉

**Comment by francescoscaringi** [comment]
Thank you! :)

**Comment by polqf** [comment]
Hi everyone, Swift 3 compatible version is already on `master` since [1.3.0](https://github.com/poolqf/FillableLoaders/releases/tag/1.3.0)

Sorry for the delay!
