### ISSUE TITLE
Thread 1: Assertion failed: The width(387.0) of the path has to fit the dimensions (Height: 287.0 Width: 287.0)

### ISSUE THREAD

**Issue by anickt** [poolqf/FillableLoaders#20]
I am getting following issue in FillableLoader.swift file when I implemet this

`Thread 1: Assertion failed: The width(387.0) of the path has to fit the dimensions (Height: 287.0 Width: 287.0)`

Below is my get path function 

`func getPath(height: Double, width: Double) -> CGPath {
    let path = CGMutablePath()
    path.move(to: CGPoint(x: 0, y: height/2))
    path.addLine(to: CGPoint(x: width + 100, y: height/2))
    path.addLine(to: CGPoint(x: width + 100, y: height*2))
    path.addLine(to: CGPoint(x: 0, y: height*2))
    path.closeSubpath()
    return path
}`

And here is code to perform animation

` let loader = WavesLoader.createLoader(with: (getPath(height: Double(Int(cell.vwBarLayout.frame.size.height)), width: Double(Int(cell.vwBarLayout.frame.size.width)))), on: cell.vwBarLayout)//WavesLoader.createProgressBasedLoaderWithPath
        loader.loaderColor = UIColor.red`

**Comment by polqf** [comment]
The path you are creating is too big

**Comment by MiladFaridnia** [comment]
Is there any way to scale down the svg to fit in its container?
