### ISSUE TITLE
Is there a way to specify the rectSize?

### ISSUE THREAD

**Issue by 690130229** [poolqf/FillableLoaders#6]
Hi, this is a wonderful project, thanks for providing this framework. but when I use this framework I can't set a value to rectSize due to I don't want to use the default one. So I add one function as below:

``` swift
 public static func createProgressBasedLoaderWithPathWithHeight(path thePath: CGPath, theHeight: CGFloat, onView: UIView? = nil) -> Self
    {
        let loader = self.init()

        loader.progressBased = true
        loader.rectSize = theHeight;
        loader.initialSetup(onView)
        loader.addPath(thePath)
        return loader
    }
```

Is this reasonable ? Thanks
Leslie

**Comment by polqf** [comment]
You have the `rectSize` public property, so you should be able to set it without extending anything :smile: 

See: https://github.com/poolqf/FillableLoaders/blob/master/Source/FillableLoader.swift#L27

**Comment by polqf** [comment]
Closing it. If this does not work for you, please reopen it
